# Generated by Django 3.0.8 on 2020-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestsmanagement', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
